(ns readme-tools
  "Generates the README's example gallery from the registry.

   The registry is the single source of truth for names and descriptions, so
   the gallery is spliced between markers rather than hand-maintained. Two bb
   tasks use this: `readme:examples` rewrites the block, and
   `readme:examples-check` fails when the block is stale or a screenshot is
   missing, which is what stops a new example landing with a broken image."
  (:require [babashka.fs :as fs]
            [clojure.string :as str]
            [examples-registry :as reg]))

(def begin-marker "<!-- BEGIN:examples (generated by `bb readme:examples`) -->")
(def end-marker "<!-- END:examples -->")

(def columns 3)

(defn demo-path
  "The screenshot path for an example, relative to the repo root."
  [name]
  (str "docs/demos/" name ".png"))

(defn missing-demos
  "Registry rows whose screenshot is not committed."
  [root]
  (remove (fn [row] (fs/exists? (fs/path root (demo-path (nth row 0)))))
          reg/examples))

(defn- cell [row]
  (let [name (nth row 0)
        desc (nth row 3)
        img  (demo-path name)]
    (str "<td width=\"33%\" valign=\"top\" align=\"center\">"
         "<a href=\"" img "\"><img src=\"" img "\" width=\"300\" alt=\"" desc "\"></a>"
         "<br><code>bb " name "</code>"
         "<br><sub>" desc "</sub>"
         "</td>")))

(defn- rows-html [group-rows]
  (str/join "\n"
            (for [chunk (partition-all columns group-rows)]
              (str "<tr>\n"
                   (str/join "\n" (map cell chunk))
                   (str/join "" (repeat (- columns (count chunk))
                                        "\n<td width=\"33%\"></td>"))
                   "\n</tr>"))))

(defn html
  "The whole generated block, markers included."
  []
  (let [grouped (reg/by-group)]
    (str begin-marker "\n\n"
         (str/join "\n\n"
                   (for [g reg/groups
                         :let [rows (get grouped g)]
                         :when (seq rows)]
                     (str "#### " g " (" (count rows) ")\n\n"
                          "<table>\n" (rows-html rows) "\n</table>")))
         "\n\n" end-marker)))

(defn splice
  "Replaces the marked block in `text`. Returns nil when either marker is
   absent, so a caller can tell a stale gallery from a missing one."
  [text block]
  (let [b (str/index-of text begin-marker)
        e (str/index-of text end-marker)]
    (when (and b e (< b e))
      (str (subs text 0 b) block (subs text (+ e (count end-marker)))))))

(defn current-block
  "The block as it stands in `text`, or nil."
  [text]
  (let [b (str/index-of text begin-marker)
        e (str/index-of text end-marker)]
    (when (and b e (< b e))
      (subs text b (+ e (count end-marker))))))
